create database sales;
use sales;
 
 CREATE TABLE customers (
  customer_id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  PRIMARY KEY (customer_id)
);
CREATE TABLE products (
  product_id INT NOT NULL AUTO_INCREMENT,
  product_name VARCHAR(100) NOT NULL,
  unit_price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  PRIMARY KEY (product_id)
);
CREATE TABLE orders (
  order_id INT NOT NULL AUTO_INCREMENT,
  order_date DATE NOT NULL,
  customer_id INT NOT NULL,
  product_id INT NOT NULL,
  PRIMARY KEY (order_id),
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

/* Insert at least five customers, five products, and ten 
orders into the respective tables. Make sure that at least 
two customers have multiple orders, and at least two 
products are included in multiple orders.*/

INSERT INTO customers (first_name, last_name, email, phone)
VALUES 
  ('John', 'Doe', 'john.doe@example.com', '555-1234'),
  ('Jane', 'Smith', 'jane.smith@example.com', '555-5678'),
  ('Bob', 'Johnson', 'bob.johnson@example.com', '555-9012'),
  ('Mary', 'Jones', 'mary.jones@example.com', '555-3456'),
  ('Tom', 'Wilson', 'tom.wilson@example.com', '555-7890');

-- Insert products
INSERT INTO products (product_name, unit_price, description)
VALUES
  ('Product A', 19.99, 'A great product'),
  ('Product B', 29.99, 'Another great product'),
  ('Product C', 9.99, 'An affordable product'),
  ('Product D', 49.99, 'A premium product'),
  ('Product E', 14.99, 'A popular product');

-- Insert orders
INSERT INTO orders (order_date, customer_id, product_id)
VALUES
  ('2023-02-15', 1, 1),
  ('2023-02-16', 2, 2),
  ('2023-02-16', 2, 3),
  ('2023-02-17', 3, 1),
  ('2023-02-17', 3, 4),
  ('2023-02-18', 4, 3),
  ('2023-02-18', 4, 5),
  ('2023-02-19', 1, 2),
  ('2023-02-20', 5, 3),
  ('2023-02-21', 2, 5);
/*Write a query that retrieves the customer's first name, 
last name, email, and the number of orders they have 
placed. The results should be ordered by the number of 
orders in descending order.
*/

select c.first_name, c.last_name, c.email, count(o.customer_id) 
from customers c join
rders o using(customer_id) 
group by o.customer_id 
order by count(o.customer_id) desc;

/* Write a query that retrieves the product name, the total 
number of orders for each product, and the total revenue 
generated by each product. The results should be ordered by 
the total revenue in descending order*/

select product_name, count(o.order_id), sum(p.unit_price) from products p join orders o using(product_id) group by product_name order by sum(unit_price) desc;
select * from products;
select * from customers;
select* from orders;

/* Write a query that retrieves the first name, last name, 
email, and product name for each order. The results should 
only include orders where the customer has placed multiple 
orders.*/

select c.first_name, c.last_name,c.email, p.product_name from customers c 
join orders o using(customer_id) 
join products p using(product_id) 
where c.customer_id in (
select customer_id from orders 
group by customer_id 
having count(*)>1)
order by customer_id;

/*Write a query that retrieves the first name, last name, and 
email for each customer who has placed at least one order 
for a product with a unit price greater than $50*/
select c.first_name, c.last_name,c.email, p.product_name from customers c 
join orders o using(customer_id) 
join products p using(product_id) ;
select c.first_name , c.last_name, c.email from customers c join orders o using(customer_id) join products p using(product_id) group by (o.customer_id) having sum(p.unit_price)>50;

/* Write a query that retrieves the product name and the 
number of times it has been ordered, but only includes 
products that have been ordered more than once.*/

select p.product_name , count(o.product_id) from products p join orders o using(product_id ) group by o.product_id having count(o.product_id)>1 ;